version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${LOCAL_UID:-1000}
        - GID=${LOCAL_GID:-1000}
    volumes:
      - ./app:/app
