version: '3.8'

services:

  app:
    image: itelmenko/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
      args:
        - UID=${LOCAL_UID:-1000}
        - GID=${LOCAL_GID:-1000}
    environment:
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}'"]
      interval: 1s
      timeout: 3s
      retries: 5