name: dockerhub-push

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Make env file
        run: make env

      - name: Run tests
        run: make ci

      - name: Build docker image
        run: make build

      - name: Push docker image
        run: make push